### Steps for Training the model for given dataset

1. Problem Statement

2. Get the data

3. Cleaning,visualizing,Feature Engineering

4. Prepare the data 

5. Select the algorithm and train the model

6. Launch and monitor,maintain the model

### Ensemble Techniques

1) Bagging

2) Boosting

### Bagging (Bootstrap Aggeregating)

Bagging is an ensemble technique where multiple models train independently on different random samples of dataset and their predictions are combined to produce a final result.

### Why Bagging?

A single decision tree does the follows:

    1) High variance

    2) Easily overfits

    3) Changes a lot if data changes slightly

Bagging reduces variance and makes predictions more stable

### How bagging works?

### Bootstrap sampling

    1) From the original dataset create multiple new datasets

    2) Each dataset is created by random sampling with replacement

    3) Each bootstrap dataset has same size as the original

    ->Some data points repeat,some data points are left out this is called out of bag samples.

### Train multiple models : 

    1) Train one model for bootstrap dataset

    2) Usually that is decision tree

    3) Each tree is trained independently

    4) Make predictions

    5) For regression take the average,for classification take the majority vote.

### Final output : 

    1) Aggregated prediction is more stable and accurate than a single decision tree

### When should we use the bagging?

    1) When dataset is medium to large

    2) Model is overfitting

    3) Decision tree give unstable result

### Boosting

Boosting is an ensemble technique where models are trained sequentially and each new model focus more on the mistakes made by the previous model.

### Why Boosting?

Boosting converts many weak learners into a strong learner.

### How boosting works?

1) Train first weak model 

2) Identify misclassified or high error points 

3) Give more importance to those points(misclassified) 

4) Train next model focusing on them

5) Repeat

6) Combine all models into a final prediction

### Boosting types

1) Ada Boost

2) Gradient Boost

3) XG Boost

### Ada Boost

Ada boost mainly focus on misclassified points

### Gradient boost

It focus on residual errors

### XG Boost

It is for the optimized solution

In [44]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

In [45]:
df=pd.read_csv("housing.csv")
df.head()

   longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [47]:
df.describe()

          longitude      latitude  ...  median_income  median_house_value
count  20640.000000  20640.000000  ...   20640.000000        20640.000000
mean    -119.569704     35.631861  ...       3.870671       206855.816909
std        2.003532      2.135952  ...       1.899822       115395.615874
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.800000     33.930000  ...       2.563400       119600.000000
50%     -118.490000     34.260000  ...       3.534800       179700.000000
75%     -118.010000     37.710000  ...       4.743250       264725.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [48]:
df['total_bedrooms']=df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [49]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [50]:
c=['median_house_value','ocean_proximity']
x=df.drop(columns=c,axis=1)
y=df['median_house_value']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [51]:
model=DecisionTreeRegressor()
g=GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=3,random_state=42)

In [52]:
g.fit(x_train,y_train)
y_pred=g.predict(x_test)
print("R2 Score : ",r2_score(y_test,y_pred))

R2 Score :  0.7668385819771691

In [53]:
g1=AdaBoostRegressor(n_estimators=100,learning_rate=0.1,random_state=42)
g1.fit(x_train,y_train)
y1_pred=g1.predict(x_test)
print("R2 Score : ",r2_score(y_test,y1_pred))

R2 Score :  0.5033645440090231

In [54]:
g2=XGBRegressor(n_estimators=100,learning_rate=0.1,random_state=42)
g2.fit(x_train,y_train)
y2_pred=g2.predict(x_test)
print("R2 Score : ",r2_score(y_test,y2_pred))

R2 Score :  0.8189904260033445